-- Optional bulk INSERT for the books table (same titles as the ORM seed in cli.py).
-- Run only if you want SQL-loaded data instead of or in addition to `flask init-db`.

INSERT INTO books (title, author, category, price_cents, description, cover_url)
VALUES
  ('1984', 'George Orwell', 'Dystopian Fiction', 1499,
   'A chilling story about surveillance, control, and truth.', '/static/img/covers/1984.svg'),
  ('To Kill a Mockingbird', 'Harper Lee', 'Classic / Historical Fiction', 1599,
   'A powerful classic about justice and compassion in the American South.', '/static/img/covers/to-kill-a-mockingbird.svg'),
  ('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic / Tragedy', 1299,
   'A tragic tale of wealth, love, and the American Dream.', '/static/img/covers/the-great-gatsby.svg'),
  ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 1799,
   'A young wizard discovers a world of magic and friendship.', '/static/img/covers/harry-potter-and-the-sorcerers-stone.svg'),
  ('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 2499,
   'An epic journey to destroy a powerful ring and save Middle-earth.', '/static/img/covers/the-lord-of-the-rings.svg'),
  ('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 1599,
   'Bilbo Baggins sets out on an unexpected adventure.', '/static/img/covers/the-hobbit.svg'),
  ('Pride and Prejudice', 'Jane Austen', 'Romance / Classic', 1299,
   'A witty romance about manners, misunderstanding, and love.', '/static/img/covers/pride-and-prejudice.svg'),
  ('The Catcher in the Rye', 'J.D. Salinger', 'Coming-of-age Fiction', 1399,
   'A teenager’s candid narration of alienation and growing up.', '/static/img/covers/the-catcher-in-the-rye.svg'),
  ('The Hunger Games', 'Suzanne Collins', 'Dystopian / Sci-Fi', 1699,
   'A deadly televised competition sparks rebellion.', '/static/img/covers/the-hunger-games.svg'),
  ('Brave New World', 'Aldous Huxley', 'Dystopian / Sci-Fi', 1499,
   'A futuristic society built on control, pleasure, and conditioning.', '/static/img/covers/brave-new-world.svg'),
  ('The Diary of a Young Girl', 'Anne Frank', 'Biography / Memoir', 1499,
   'Anne Frank’s moving diary written during World War II.', '/static/img/covers/the-diary-of-a-young-girl.svg'),
  ('Long Walk to Freedom', 'Nelson Mandela', 'Autobiography', 1999,
   'Mandela’s autobiography about resilience and justice.', '/static/img/covers/long-walk-to-freedom.svg'),
  ('Steve Jobs', 'Walter Isaacson', 'Biography', 1999,
   'A biography of Apple co-founder Steve Jobs.', '/static/img/covers/steve-jobs.svg'),
  ('Becoming', 'Michelle Obama', 'Memoir', 1899,
   'Michelle Obama’s personal story and journey.', '/static/img/covers/becoming.svg'),
  ('The Wright Brothers', 'David McCullough', 'Biography', 1799,
   'The inspiring story of the brothers who invented flight.', '/static/img/covers/the-wright-brothers.svg'),
  ('Educated', 'Tara Westover', 'Memoir', 1799,
   'A memoir about family, education, and transformation.', '/static/img/covers/educated.svg'),
  ('I Am Malala', 'Malala Yousafzai', 'Biography / Memoir', 1699,
   'The story of Malala and the fight for education.', '/static/img/covers/i-am-malala.svg'),
  ('The Glass Castle', 'Jeannette Walls', 'Memoir', 1599,
   'A memoir of a childhood shaped by poverty and resilience.', '/static/img/covers/the-glass-castle.svg'),
  ('Born a Crime', 'Trevor Noah', 'Memoir / Humor', 1699,
   'A funny and moving memoir about growing up in South Africa.', '/static/img/covers/born-a-crime.svg'),
  ('When Breath Becomes Air', 'Paul Kalanithi', 'Memoir', 1599,
   'A reflection on life, death, and meaning by a neurosurgeon.', '/static/img/covers/when-breath-becomes-air.svg'),
  ('Dune', 'Frank Herbert', 'Science Fiction', 1899,
   'A sci-fi epic of politics, prophecy, and survival on Arrakis.', '/static/img/covers/dune.svg'),
  ('Foundation', 'Isaac Asimov', 'Science Fiction', 1699,
   'A classic saga about preserving knowledge in a collapsing empire.', '/static/img/covers/foundation.svg'),
  ('Ender''s Game', 'Orson Scott Card', 'Science Fiction', 1699,
   'A gifted child is trained to defend humanity in space war.', '/static/img/covers/enders-game.svg'),
  ('The Martian', 'Andy Weir', 'Science Fiction', 1799,
   'An astronaut uses science and humor to survive on Mars.', '/static/img/covers/the-martian.svg'),
  ('Neuromancer', 'William Gibson', 'Cyberpunk / Sci-Fi', 1599,
   'A cyberpunk classic that helped define the genre.', '/static/img/covers/neuromancer.svg'),
  ('Snow Crash', 'Neal Stephenson', 'Cyberpunk / Sci-Fi', 1699,
   'A fast-paced cyberpunk adventure in a hyper-connected world.', '/static/img/covers/snow-crash.svg'),
  ('Ready Player One', 'Ernest Cline', 'Sci-Fi / Adventure', 1599,
   'A virtual reality treasure hunt packed with pop culture.', '/static/img/covers/ready-player-one.svg'),
  ('The Time Machine', 'H.G. Wells', 'Sci-Fi / Classic', 1199,
   'A classic story of time travel and the future of humanity.', '/static/img/covers/the-time-machine.svg'),
  ('Frankenstein', 'Mary Shelley', 'Sci-Fi / Gothic', 1199,
   'A foundational gothic tale about creation and responsibility.', '/static/img/covers/frankenstein.svg'),
  ('Jurassic Park', 'Michael Crichton', 'Sci-Fi / Thriller', 1699,
   'A techno-thriller where resurrected dinosaurs go wrong.', '/static/img/covers/jurassic-park.svg'),
  ('The Da Vinci Code', 'Dan Brown', 'Mystery / Thriller', 1599,
   'A fast-paced mystery involving secrets, symbols, and history.', '/static/img/covers/the-da-vinci-code.svg'),
  ('Gone Girl', 'Gillian Flynn', 'Thriller / Mystery', 1599,
   'A twisty thriller about a marriage and a disappearance.', '/static/img/covers/gone-girl.svg'),
  ('Sherlock Holmes: A Study in Scarlet', 'Arthur Conan Doyle', 'Mystery / Detective', 1099,
   'The first Sherlock Holmes mystery and introduction to Watson.', '/static/img/covers/sherlock-holmes-a-study-in-scarlet.svg'),
  ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Crime / Thriller', 1699,
   'A dark mystery involving a missing person and hidden crimes.', '/static/img/covers/the-girl-with-the-dragon-tattoo.svg'),
  ('Big Little Lies', 'Liane Moriarty', 'Mystery / Drama', 1599,
   'Secrets and drama build to a shocking event.', '/static/img/covers/big-little-lies.svg'),
  ('In the Woods', 'Tana French', 'Crime / Mystery', 1599,
   'A detective novel with psychological depth and suspense.', '/static/img/covers/in-the-woods.svg'),
  ('The Silent Patient', 'Alex Michaelides', 'Psychological Thriller', 1699,
   'A therapist tries to uncover why a patient stopped speaking.', '/static/img/covers/the-silent-patient.svg'),
  ('And Then There Were None', 'Agatha Christie', 'Mystery', 1299,
   'A classic mystery where guests are eliminated one by one.', '/static/img/covers/and-then-there-were-none.svg'),
  ('The Woman in the Window', 'A.J. Finn', 'Thriller', 1599,
   'A psychological thriller about what was (or wasn’t) seen.', '/static/img/covers/the-woman-in-the-window.svg'),
  ('The Reversal', 'Michael Connelly', 'Legal Thriller', 1499,
   'A legal thriller involving a high-profile reversal case.', '/static/img/covers/the-reversal.svg'),
  ('The Alchemist', 'Paulo Coelho', 'Philosophical Fiction', 1399,
   'A story about purpose, destiny, and following your dream.', '/static/img/covers/the-alchemist.svg'),
  ('Life of Pi', 'Yann Martel', 'Adventure / Philosophical Fiction', 1499,
   'A survival story with philosophical and spiritual themes.', '/static/img/covers/life-of-pi.svg'),
  ('The Kite Runner', 'Khaled Hosseini', 'Historical Fiction / Drama', 1599,
   'A powerful novel about friendship, guilt, and redemption.', '/static/img/covers/the-kite-runner.svg'),
  ('A Thousand Splendid Suns', 'Khaled Hosseini', 'Historical Fiction', 1599,
   'A moving story of love and resilience across generations.', '/static/img/covers/a-thousand-splendid-suns.svg'),
  ('The Book Thief', 'Markus Zusak', 'Historical Fiction', 1499,
   'A WWII story narrated by Death, centered on books and hope.', '/static/img/covers/the-book-thief.svg'),
  ('The Road', 'Cormac McCarthy', 'Post-Apocalyptic Fiction', 1499,
   'A stark journey of survival between father and son.', '/static/img/covers/the-road.svg'),
  ('The Fault in Our Stars', 'John Green', 'Romance / Drama', 1499,
   'A heartfelt romance about two teens facing illness.', '/static/img/covers/the-fault-in-our-stars.svg'),
  ('Me Before You', 'Jojo Moyes', 'Romance / Drama', 1499,
   'A romance that explores love, choice, and change.', '/static/img/covers/me-before-you.svg'),
  ('The Help', 'Kathryn Stockett', 'Historical Fiction', 1599,
   'A story of courage and friendship in 1960s Mississippi.', '/static/img/covers/the-help.svg'),
  ('Where the Crawdads Sing', 'Delia Owens', 'Mystery / Drama', 1699,
   'A mystery and coming-of-age story set in the marshes.', '/static/img/covers/where-the-crawdads-sing.svg');

